include:
  - component: gitlab.com/defense-unicorns/gitlab-components/build-image-component/build-image@main
    inputs:
      stage: build-image
      dockerfile-path: Dockerfile
  - component: gitlab.com/defense-unicorns/gitlab-components/zarf-component/zarf-setup@main
    inputs:
      stage: build
  - component: gitlab.com/defense-unicorns/gitlab-components/zarf-component/zarf-package-publish@main
    inputs:
      stage: publish
      path: zarf-package-*.zst
      destination_registry: "oci://ttl.sh/zarf"

stages: [build-image, build, publish]

zarf-pkg:
  stage: build
  needs: 
    - zarf_setup
  script:
    - ./zarf package create . --confirm --set VERSION=${CI_COMMIT_SHORT_SHA} --set IMAGE=${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}

zarf_package_publish:
  needs: 
    - zarf-pkg
  dependencies: 
    - zarf-pkg
