include:
  - component: gitlab.com/defense-unicorns/gitlab-components/zarf-component/zarf-setup@main
    inputs:
      stage: build

stages: [build]

zarf-pkg:
  stage: build
  needs: [zarf_setup]
  script:
    - zarf version