apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-python
  namespace: hello-world-python
  labels:
    app: hello-world-python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-python
  template:
    metadata:
      labels:
        app: hello-world-python
    spec:
      containers:
        - name: hello-world-python
          image: registry.furiousfive.dev/swf-pipeline/hello-world-python:eeb3a7e1
          ports:
            - containerPort: 8080
